### ISSUE TITLE
Liana.collection not working

### ISSUE THREAD

**Issue by alexprice1** [ForestAdmin/forest-express#109]
It looks like this line is writing over what I might had described earlier when I used Liana.collection():
https://github.com/ForestAdmin/forest-express/blob/devel/generators/schemas.js#L18

I remember that Liana.collection used to work, but now it doesn't. I'm not sure if reconciliation was happening somewhere else, because this file has not been changed in some time.

Any help is appreciated!

**Comment by arnaudbesnier** [comment]
I just saw your email, I paste here the code you sent us for the record:

```javascript
 app.get('/forest/opportunity/:opportunityId/relationships/registrations', getRegistrations);
  Liana.collection('opportunities', {
    fields: [{
      field: 'registrations',
      type: ['String'],
      reference: 'registrations.id'
    }]
  });
  app.use(Liana.init({
    modelsDir: require('path').join(__dirname, '../models'), // Your models directory.
    envSecret: process.env.FOREST_ENV_SECRET,
    authSecret: process.env.FOREST_AUTH_SECRET,
    mongoose,
  }));
  Registration
    .find({
    })
    .then((movies) => {
      return new Liana.Serializer(Liana, mongoose.models.movies, movies, null, {}, {
        count: movies.length
      }).perform();
    })
    .then((projects) => res.send(projects))
    .catch(next);
}
```

**Comment by arnaudbesnier** [comment]
I think you should put the `Liana.init` at the beginning, and then call `Liana.collection` to declare your Smart Relationship.

**Comment by alexprice91** [comment]
Thanks for the reply! I'm using `forest-express-mongoose`: 1.2.4 which uses `forest-express`: 1.2.6


So I have tried switching those around. I was able to implement a change to the code that "fixed" it for me. Let me fork the repo and put the commit here...

**Comment by alexprice91** [comment]
Here is my commit that fixes it for me:
https://github.com/terraindigital/forest-express/commit/153fdffd4033e9c356e405bf864aabf99d2517b2

Basically I queue up the Liana.collection operations and then execute them after Liana.init.

**Comment by arnaudbesnier** [comment]
@alexprice1 what you should actually do is configure your Smart Fields in the `forest` directory.
This is the mainstream way to do it. You can follow this example: https://doc.forestadmin.com/developer-guide/express-mongoose.html#example-concatenate-first-and-last-names
