### ISSUE TITLE
Smart Fields - Help me make sense of the implementation of setters in collections

### ISSUE THREAD

**Issue by louisremi** [ForestAdmin/forest-express#141]
So far I had been using a maximum of 1 async setter per collection in my code. Last week I created many smart fields with async setters to implement a gallery admin. And things went awry!

The best way to illustrate all the bugs I encountered is to comment the [snippet implementing setters in collections](https://github.com/ForestAdmin/forest-express/blob/devel/deserializers/resource.js#L37) (`///` comments are mine):
```js
return P
  /// Looping on `smartFields` which is an array of all virtual fields with setters.
  /// Let's keep that in mind…
  .each(smartFields, function (field) {
    // WARNING: The Smart Fields setters may override other changes.
    /// The `attributes` object is passed by reference, so it's already possible to modify it.
    /// Why is it mandatory to return it from every setter then?

    /// Is the following condition supposed to test if the setter is async?
    /// This actually tests if the setter is itself a promise, which is probably never true.
    /// I believe this whole block is useless, async results are already dealt with by `P.each(…`
    if (_.isFunction(field.set.then)) {
      return field.set(attributes, attributes[field.field])
        .then(function (newAttributes) {
          attributes = newAttributes;
          return attributes;
        });
    } else {
      /// So each setter is called with `attributes`, no matter if the value of that field has
      /// actually been updated or not… 
      /// Bug 1: most of the time my fields ended up having their value reset to `undefined`
      /// because of the way this code is written.
      attributes = field.set(attributes, attributes[field.field]);
      /// Bug 2: since the above `if` doesn't actually deal with promise results,
      /// having 1 async setter breaks all other setters, which are called with that promise :-(
      return attributes;
    }
})
```

I have fixed all my problems at once by replacing the above snippet with the following one:
```js
return P
  .each(smartFields, function (field) {
    if ( field.field in attributes ) {
      return field.set(attributes, attributes[field.field]);
    }
  })
```

I would really like to get this code change merged into the official forest-express, but first I wanted to make sure I understood why the current code was written that way.

**Comment by arnaudbesnier** [comment]
Hi @louisremi, your implementation is very light, and so, very attractive :)

My first thoughts are:
- `This actually tests if the setter is itself a promise, which is probably never true` => I can assure you that it can be true. The implementation of Forest allow you to define a setter that can return a promise.
- `The attributes object is passed by reference, so it's already possible to modify it` => You're probably right about that we could simplify this code. And then, whatever you return in you setters (promise or not), `field.set(attributes, attributes[field.field])` should be enough.

Let's try test your implementation on our side and merge this if everything is fine!

**Comment by louisremi** [comment]
@arnaudbesnier Thanks for having a look at it :-)

> This actually tests if the setter is itself a promise, which is probably never true

Let me try to rephrase that: Instead of testing if the setter *returns* a promise (which is useful and which I use), the current implementation tests if the setter *is itself* a promise (which I believe is never true).

**Comment by arnaudbesnier** [comment]
Got it! My bad... We'll definitely fix this code.

**Comment by arnaudbesnier** [comment]
@louisremi your fix has been released in the latest Express liana versions:

- Express-Sequelize 2.2.6
- Express-Mongoose 2.1.2

Thanks for the contribution,
🌲🌲🌲

**Comment by louisremi** [comment]
Yay!
