### ISSUE TITLE
Add support for custom routes for Smart Actions

### ISSUE THREAD

**Issue by jdonzet** [ForestAdmin/forest-express#168]
Smart actions maps automatically the action name to the action route converting to lowercase and replacing spaces with -
`
Cancel Order => cancel-order
`

There is no way to allow an smart action to be displayed like "Cancel" but the route be "cancel-order" or "cancel-payment" in the same app.

Another use case is to display an action in some Language different to english but keep code in english.

**Comment by arnaudbesnier** [comment]
hey @jdonzet, you can actually do this with current Forest lianas.
The `endpoint` option should do the job for your use cases.

<img width="880" alt="screen shot 2018-04-29 at 21 09 39" src="https://user-images.githubusercontent.com/664261/39410052-dd5c004e-4bf1-11e8-9ea5-da7120a13a9f.png">

**Comment by arnaudbesnier** [comment]
No problem. The screenshot is from the "Lumber" part of the documentation (Lumber uses the forest-express-sequelize). This part of the documentation is more recent than the express-sequelize and express-mongoose documentation. This is actually our fault, with a better documentation, you would never have posted an issue.

🌲🌲🌲

**Comment by jdonzet** [comment]
Doesn't work with current version of forest-express-mongoose@2.8.3
When endpoint is specified, no api call is made from the admin web app (I checked the network traffic to confirm it).
If no endpoint is specified, everything works fine.

**Comment by arnaudbesnier** [comment]
Hey @jdonzet, here is an example of code that perfectly works on my side:

```javascript
const Liana = require('forest-express-mongoose');

Liana.collection('Customer', {
  actions: [{
    name: 'Refresh cache',
    endpoint: '/forest/customer/actions/refresh-cache',
  }],
});
```
