### ISSUE TITLE
Publish ip-utils as a package to avoid the need for git when installing forest-express

### ISSUE THREAD

**Issue by Caerbannog** [ForestAdmin/forest-express#169]
## Expected behavior

`npm install forest-express` should work on machines where git is not installed.
Example: a Dockerfile based on Alpine Linux.

## Actual behavior

Error message: `error Couldn't find the binary git`

## Cause

Here is the dependency that is locked on a git version:
https://github.com/ForestAdmin/forest-express/blob/bc2bfa121685b79d94271136e919769442f0289b/package.json#L34

**Comment by ozomer** [comment]
This is relevant for anyone that uses dockers based on node-alpine.
You have to add a line like: `RUN apk add --no-cache git` to install git on the image.

**Comment by Kerumen** [comment]
This is blocking my installation on now (https://github.com/zeit/now-builders/issues/49). Can you do something please?

**Comment by arnaudbesnier** [comment]
Hi @Caerbannog, @rodrigo4244, @Kerumen this is now fixed in the latest liana versions.
Thank you for your patience.
