### ISSUE TITLE
_.isEmpty if statement blocking code execution

### ISSUE THREAD

**Issue by romainisnel** [ForestAdmin/forest-express#19]
I first tried to use the collection method to create a new action on the admin panel. I followed the steps in the developper guide but everytime I started my server I got this error :

 [forest] 🌳🌳🌳  Cannot customize your collection named "contents" properly. Did you call the "collection" method in the /forest directory?

I tried a lot of solutions but none had worked. After inspecting the code, I've seen that this part of the code was blocking the execution.

```
if (_.isEmpty(Schemas.schemas)) {
    logger.error('Cannot customize your collection named "' + name +
      '" properly. Did you call the "collection" method in the /forest ' +
      'directory?');
    return;
}
```

The Schemas.schemas object was not empty but the code systematically entered in the if statement. After commenting this part of the code, everything worked, the server launched and the actions were available and working on the Admin panel.

**Comment by SeyZ** [comment]
Hey @romainisnel Thanks for the issue!

It seems your file `/forest/user.js` is require **before** the inspection of your models.
Did you require manually the file `/forest/user.js`?

**Comment by romainisnel** [comment]
Yes I required it manually. But after removing the require, it still work. So I'm not sure of how it works. The guide is not super clear about that.

**Comment by arnaudbesnier** [comment]
Actually, all files inside `/forest` directory are required automatically by the liana.
We might need to update our documentation about this.

Without the manual require, it seems to work properly on your project.
Is everything fine now?

**Comment by SeyZ** [comment]
I close the issue. @romainisnel Don't hesitate to reopen it if you still have the problem.
Thanks for report, we'll clarify this on our documentation

**Comment by romainisnel** [comment]
Yes everything is fine. It might be a great thing to detail the documentation a bit. Forest is really cool.
