### ISSUE TITLE
Problem : prefill a form with dynamic default values

### ISSUE THREAD

**Issue by XavierColombel** [ForestAdmin/forest-express#205]
In Actions, I'm trying to prefill a form with dynamic default values. So I used the example [here](https://doc.forestadmin.com/developer-guide/express-mongoose.html#prefill-a-form-with-default-values) and it's like `value` function has no effect on fields. No field is prefilled.

```javascript
Liana.collection('customers', {
  actions: [{
    name: 'Send money',
    fields: [{
      field: 'amount',
      isRequired: true,
      description: 'Amount',
      type: 'Number'
    }]
  }],
  values: (context) => {
      return {
        amount: 123
      };
  }
});
```

I'm running on Express server.

**Comment by arnaudbesnier** [comment]
Hi @XavierColombel, thanks for the feedback.

This is a documentation issue in the Mongoose section.
The following code:
```javascript
Liana.collection('customers', {
  actions: [{
    name: 'Send money',
    fields: [{
      field: 'amount',
      isRequired: true,
      description: 'Amount',
      type: 'Number'
    }],
    values: (context) => {
      return {
        amount: 123
      };
    }
  }]
});
``` 
should work as expected.

We'll do the documentation fix next week.

🌲🌲🌲

**Comment by XavierColombel** [comment]
Thanks @arnaudbesnier but it's not working. Maybe you should try by yourself before you fix the documentation. It might be a bug elsewhere.

**Comment by arnaudbesnier** [comment]
Maybe you should follow this documentation example:
https://doc.forestadmin.com/developer-guide/lumber.html#prefill-a-form-with-default-values

This feature is available on `Single` action type only. You need to specify this in your action too I guess.

Do you use the latest liana version?

**Comment by XavierColombel** [comment]
I use the last version of Liana `"forest-express-mongoose": "^2.14.5"` and when I put `type="single"`, in an action, it simply removes all custom actions from the list.

```javascript
Liana.collection("customers", {
	actions: [
		{
			name: "Send money",
			type: "single",
			fields: [
				{
					field: "amount",
					isRequired: true,
					description: "Amount",
					type: "Number",
				},
			],
			values: context => {
				console.log(context);
				return {
					amount: 123,
				};
			},
		},
	],
});
```

**Comment by arnaudbesnier** [comment]
@XavierColombel, this is what I just tried:
```javascript
Liana.collection('invoice', {
  actions: [{
    name: 'Charge',
    type: 'single',
    fields: [{
      field: 'foo',
      type: 'String',
    }, {
      field: 'value',
      type: 'Number',
    }],
    values() {
      return {
        foo: 'bar',
        value: 42,
      };
    },
  }],
});
```
and it worked as expected:

<img width="674" alt="screen shot 2018-10-20 at 18 11 35" src="https://user-images.githubusercontent.com/664261/47257863-a2b74180-d493-11e8-9766-c5ec3ec2026c.png">

**Comment by XavierColombel** [comment]
It should be another problem. It's definitely not working on my side. Here is a video of my files and how it works, if you wanna have a look : [https://streamable.com/s/0sgsc/fsmyuw](https://streamable.com/s/0sgsc/fsmyuw)

**Comment by arnaudbesnier** [comment]
Hi @XavierColombel,

"Single" actions are actions only available from a record detail view. So, it is normal that, in your screencast, when you set the action as "Single" it disappears from the collection list actions.
You have to click on a record to be able to the see the action.
(See https://doc.forestadmin.com/developer-guide/lumber.html#configuring-the-accessibility-of-a-smart-action for more details). 

Second point, the form pre-fill feature is only available only on "Single" type actions.

Let me know if your issue persists.

**Comment by XavierColombel** [comment]
@arnaudbesnier thank you for this explanation, it's clear for me now. I hope you could add this feature to list view, soon. 👍

**Comment by XavierColombel** [comment]
@arnaudbesnier, it's not working with Enums, right?

**Comment by robertvanhoesel** [comment]
Any plans to support settings default values on a bulk action?

The documentation does not mention this only works on single actions, took me quite some time to figure out it doesn't work on bulk. @arnaudbesnier – maybe update the docs to mention this?

**Comment by arnaudbesnier** [comment]
Hi @robertvanhoesel,

Do the default values you want to set in the Smart Action form depend on the selected records?
If those values are always the same, you should be able to use the `defaultValue` option on the declared Smart Action fields.

The documentation mentions that the `values` function can be implemented for "single" actions only:
https://docs.forestadmin.com/documentation/reference-guide/actions/create-and-manage-smart-actions#prefill-a-form-with-default-values

<img width="771" alt="Screenshot 2019-07-21 at 22 47 25" src="https://user-images.githubusercontent.com/664261/61596958-493e9780-ac0a-11e9-84d0-6f842906e4fb.png">

**Comment by robertvanhoesel** [comment]
Hi @arnaudbesnier,

It's the same default value for all records. I was not aware of the defaultValue option, that definitely does the trick. Thanks!
