### ISSUE TITLE
Updating 2 collections at same time

### ISSUE THREAD

**Issue by XavierColombel** [ForestAdmin/forest-express#206]
I need to update 2 collections at same time.

Right know, here is the simplified structure of my collections:

**./models/Batch**
```javascript
const batchSchema = new mongoose.Schema({
	name: String,
	users: [
		{
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
		},
	],
});
const Batch = mongoose.model("Batch", batchSchema);
module.exports = Batch;
```

**./models/User**
```javascript
const userSchema = new mongoose.Schema({
	firstname: String,
	lastname: String,
	batch: {
	        type: mongoose.Schema.Types.ObjectId,
		ref: "Batch"
        }
});
const User = mongoose.model("User", userSchema);
module.exports = User;
```

Once I assign a `batch` value to an item in the `User` collection, I need to update the `Batch` collection to add the `user._id` in the array. Any way to do that?

**Comment by arnaudbesnier** [comment]
Hi @XavierColombel, I think you can use Smart Routes to adapt the behaviour of your ForestAdmin User update controller.
See the explanation in ForestAdmin documentation here:
https://docs.forestadmin.com/documentation/reference-guide/routes

If this is a behaviour you need not only for your admin app but also for your customer facing app, maybe you should consider Mongoose hooks:
https://mongoosejs.com/docs/middleware.html#order
