### ISSUE TITLE
forestadmin-schema.json created in the wrong directory

### ISSUE THREAD

**Issue by cylwin** [ForestAdmin/forest-express#266]
Sorry for the quality of the issue.

My .forestadmin-schema.json was in my server directory.
When i run my code in dev, I sometime,
`cd server; node index.js`
But in production I run
`node server/index.js`
I think, it's an issue. You should create the file, relatively from the index.js and not from where you run the command line. Imagine I run the server with a super long absolute path.

arnaud:f-forest:  il y a 5 minutes
The file is created in the project repository (nowhere else). But, indeed the code does not work properly if you run your server without being in the server repository.
Could create an issue in the forest-express repository (https://github.com/ForestAdmin/forest-express/issues)?
The issue looks to be here:
https://github.com/ForestAdmin/forest-express/blob/devel/src/index.js#L31

**Comment by arnaudbesnier** [comment]
Hi @cylwin,

Thank you for the feedback.
A fix is available in all `forest-express` packages:
- `forest-express@5.3.0`
- `forest-express-sequelize@5.3.0`
- `forest-express-mongoose@5.3.0`

Feel free to re-open the ticket, if the issue persists once upgraded.

🌲🌲🌲
