### ISSUE TITLE
Intercom requires the use of access tokens

### ISSUE THREAD

**Issue by gcoombe** [ForestAdmin/forest-express#56]
As of January 2017 intercom requires that access tokens be used rather than apiKeys (https://developers.intercom.com/reference). 

As a new user of intercom (post January) I do not have the ability to generate an apiKey and therefore cannot use this integration.

**Comment by alexprice91** [comment]
bump

**Comment by arnaudbesnier** [comment]
@gcoombe, @alexprice91 you can review the PR and approve it (or not 😄).

Thanks guys!
🌲🌲🌲

**Comment by arnaudbesnier** [comment]
@gcoombe @alexprice91 we would love your feedback on the fix!

**Comment by gcoombe** [comment]
Sorry about the slow response! LGTM

**Comment by arnaudbesnier** [comment]
The fix is now available in the latest liana versions.

🌲🌲🌲
