### ISSUE TITLE
/forest directory must be at the project route.

### ISSUE THREAD

**Issue by jordan-burnett** [ForestAdmin/forest-express#6]
At the moment when I want to add a smart field, I have to add a file to a directory called 'forest' at the route of my project, which is included when the server initializes.

This causes problems for my current set-up, where I'm using babel to transpile ES6 code, as my uncompiled code exists in a 'src' directory and therefore the directory is at 'src/forest'.

The line that enforces this is 215 in index.js:

`return requireAllModels(Implementation, path.resolve('.') + '/forest')`

It would be good to be able to define this in the same way as 'modelsDir' during initialization.

An even nicer API would be if I could call liana.collection() separately in my apps existing initialization sequence.  It seems to me this would open up more options for custom setups like mine not to have to rely on putting all Forest specific code in one predetermined directory

**Comment by VinzGhyz** [comment]
Anything that is under the Forest folder is automatically loaded as Forest config, but you are not required to put your smart fields' declaration there. As long as your declaration is loaded into your app alongside Forest's initialization, it should be picked up.

If you want to still keep logic specific to Forest in its dedicated folder, you could add said folder to be ignored in your `babelrc` file.

As far as having it configurable, that's something we'll have to look into but could definitely be implemented.

**Comment by GautierT** [comment]
+1 for this feature !

**Comment by GautierT** [comment]
@VinzGhyz : 
I tried to declare my smart actions elsewhere (like in my router config) but it's picked up too early by Forest so i have this error : `[forest] 🌳🌳🌳  Cannot customize your collection named "demarches" properly. Did you call the "collection" method in the /forest directory?`
Where should i put it ? 

I have exactly the same config that @jordan-burnett : babel transpiling my src folder to a dist folder.

**Comment by arnaudbesnier** [comment]
The feature is now in code review and will be released soon.
Thank you guys for the feedback!

**Comment by arnaudbesnier** [comment]
The new option will be: 
```
app.use(require('forest-express-mongoose').init({
    modelsDir: __dirname + '/models',  // Your models directory.
    smartDir: __dirname + '/my/forest/custom/directory',  // Your Forest Smart implementation directory.
    envSecret: config.forest.env_secret,
    authSecret: config.forest.auth_secret,
    mongoose: mongoose // The database connection.
}));
```
