### ISSUE TITLE
Allow external endpoint on smart action

### ISSUE THREAD

**Issue by whollacsek** [ForestAdmin/forest-express#629]
https://github.com/ForestAdmin/forest-express/blob/feb5ecc7658adc68f48e7f3f6dc098d6404c682b/src/services/path.js#L12

It would be great if we can use an external endpoint for smart actions. It is especially useful in a serverless architecture. Currently we need to write an indirection in the routes folder to forward the request.

**Comment by louisteenbrink** [comment]
@whollacsek have you tried adding the[ endpoint option](https://docs.forestadmin.com/documentation/reference-guide/actions/create-and-manage-smart-actions#available-smart-action-options) to your smart action configuration?
