### ISSUE TITLE
deprecated res.send(status)

### ISSUE THREAD

**Issue by piotr-s-brainhub** [ForestAdmin/forest-express#86]
could you upgrade express-cors to the newest version?

because I obtain
```
express deprecated res.send(status): Use res.sendStatus(status) instead node_modules/express-cors/index.js:95:45
```

**Comment by arnaudbesnier** [comment]
@piotr-s-brainhub thanks for the feedback.

Feel free to contribute, I would be happy to remove this deprecation warning.

**Comment by arnaudbesnier** [comment]
@piotr-s-brainhub please upgrade to the latest liana version you use to have the fix.
