### ISSUE TITLE
Add Fastify support

### ISSUE THREAD

**Issue by playleaks** [ForestAdmin/forest-express#870]
## Expected behavior

Please support also Fastify framework with another dedicated repo or with some adaptation of the express implementation.
I tried to manually convert every single route and dependencies, but it's an huge job and involves the 2 dependencies forest-express and forest-express-mongoose plus your custom project files.
I need help! Thanks

## Actual behavior

TODO: What is the current behavior?

## Failure Logs

TODO: Please include any relevant log snippets, if necessary.

## Context

TODO: Please provide any relevant information about your setup.

* Package Version:
* Express Version:

**Comment by Thenkei** [comment]
You can give a try to [our latest agent for Node.js `@forestadmin/agent`](https://github.com/ForestAdmin/agent-nodejs)

You can find all related documentation here. https://docs.forestadmin.com/developer-guide-agents-nodejs/getting-started/install/expose-an-http-endpoint/using-fastify

And a complete guide on how to migrate to this new agent. https://docs.forestadmin.com/developer-guide-agents-nodejs/getting-started/migrating
