### ISSUE TITLE
404 error when accessing a custom GET route

### ISSUE THREAD

**Issue by bidhan-a** [ForestAdmin/forest-express#94]
I've defined a get route for a smart collection as mentioned in the documentation but I keep getting a 404 error. Any suggestions?

Thanks.

**Comment by arnaudbesnier** [comment]
Hi @bidhan-a, we'd love to help you. But we need you whole Smart Collection implementation to check that everything looks good.

It might also be one of your express project middleware that could respond 404 before hitting the custom route you created.

**Comment by bidhan-a** [comment]
Hello @arnaudbesnier ,

Thanks for the response. I've actually managed to resolve this issue. I was following along with the [documentation](http://doc.forestadmin.com/developers-guide/#smart-collections) on how to define a custom GET route. It mentions the following:

`router.get('/forest/brands', Liana.ensureAuthenticated, function (req, res) {...})`

But it doesn't work that way. It should only be 

`router.get('/brands', Liana.ensureAuthenticated, function (req, res) {})`

because '/forest' is already defined inside app.js.

**Comment by arnaudbesnier** [comment]
Thanks @bidhan-a ! Cool to see that you made it work.

I don't really understand why the route declaration:
`router.get('/forest/brands', Liana.ensureAuthenticated, function (req, res) {...})`
does not work as described in the documentation.

What do you mean, saying "'/forest' is already defined inside app.js"?

**Comment by bidhan-a** [comment]
Hi @arnaudbesnier ,

I was referring to this block of code:

```
fs.readdirSync('./routes').forEach((file) => {
  if (file !== '.gitkeep') {
    app.use('/forest', require('./routes/' + file));
  }
});
```
The app is already "using" '/forest' here, so I think defining just '/brands' instead of '/forest/brands'  would work fine.

**Comment by arnaudbesnier** [comment]
@bidhan-a I finally understood your point... Seems to make sense.
We need to fix the doc about this.
